### ISSUE TITLE
正文内容样式可以美化下的

### ISSUE THREAD

**Issue by tza17313** [ruanyf/es6tutorial#64]
``` css
#content{
    font-size:1.2rem;
    width:auto;
    margin-right:20px;
    font-family:"Segoe UI","Lucida Grande",Helvetica,Arial,"Microsoft YaHei",FreeSans,Arimo,"Droid Sans","wenquanyi micro hei","Hiragino Sans GB","Hiragino Sans GB W3",Arial,sans-serif;
    line-height:1.8;
}
```
